# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/tinyb-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/tinyb-master/build

# Include any dependencies generated for this target.
include java/jni/CMakeFiles/javatinyb.dir/depend.make

# Include the progress variables for this target.
include java/jni/CMakeFiles/javatinyb.dir/progress.make

# Include the compile flags for this target's objects.
include java/jni/CMakeFiles/javatinyb.dir/flags.make

java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o: ../java/jni/BluetoothAdapter.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothAdapter.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothAdapter.cxx > CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothAdapter.cxx -o CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o: ../java/jni/BluetoothDevice.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothDevice.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothDevice.cxx > CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothDevice.cxx -o CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o: ../java/jni/BluetoothEvent.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothEvent.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothEvent.cxx > CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothEvent.cxx -o CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o: ../java/jni/BluetoothGattCharacteristic.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattCharacteristic.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattCharacteristic.cxx > CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattCharacteristic.cxx -o CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o: ../java/jni/BluetoothGattDescriptor.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattDescriptor.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattDescriptor.cxx > CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattDescriptor.cxx -o CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o: ../java/jni/BluetoothGattService.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattService.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattService.cxx > CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothGattService.cxx -o CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o: ../java/jni/BluetoothManager.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothManager.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothManager.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothManager.cxx > CMakeFiles/javatinyb.dir/BluetoothManager.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothManager.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothManager.cxx -o CMakeFiles/javatinyb.dir/BluetoothManager.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o


java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o: ../java/jni/BluetoothObject.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/BluetoothObject.cxx

java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/BluetoothObject.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/BluetoothObject.cxx > CMakeFiles/javatinyb.dir/BluetoothObject.cxx.i

java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/BluetoothObject.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/BluetoothObject.cxx -o CMakeFiles/javatinyb.dir/BluetoothObject.cxx.s

java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o


java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o: ../java/jni/JNIMem.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/JNIMem.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/JNIMem.cxx

java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/JNIMem.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/JNIMem.cxx > CMakeFiles/javatinyb.dir/JNIMem.cxx.i

java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/JNIMem.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/JNIMem.cxx -o CMakeFiles/javatinyb.dir/JNIMem.cxx.s

java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o


java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o: java/jni/CMakeFiles/javatinyb.dir/flags.make
java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o: ../java/jni/helper.cxx
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/javatinyb.dir/helper.cxx.o -c /home/pi/Desktop/tinyb-master/java/jni/helper.cxx

java/jni/CMakeFiles/javatinyb.dir/helper.cxx.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/javatinyb.dir/helper.cxx.i"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/Desktop/tinyb-master/java/jni/helper.cxx > CMakeFiles/javatinyb.dir/helper.cxx.i

java/jni/CMakeFiles/javatinyb.dir/helper.cxx.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/javatinyb.dir/helper.cxx.s"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/Desktop/tinyb-master/java/jni/helper.cxx -o CMakeFiles/javatinyb.dir/helper.cxx.s

java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.requires:

.PHONY : java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.requires

java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.provides: java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.requires
	$(MAKE) -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.provides.build
.PHONY : java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.provides

java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.provides.build: java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o


# Object files for target javatinyb
javatinyb_OBJECTS = \
"CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o" \
"CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o" \
"CMakeFiles/javatinyb.dir/JNIMem.cxx.o" \
"CMakeFiles/javatinyb.dir/helper.cxx.o"

# External object files for target javatinyb
javatinyb_EXTERNAL_OBJECTS =

java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/build.make
java/jni/libjavatinyb.so.0.5.0: /usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/libjawt.so
java/jni/libjavatinyb.so.0.5.0: /usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/server/libjvm.so
java/jni/libjavatinyb.so.0.5.0: src/libtinyb.so.0.5.0
java/jni/libjavatinyb.so.0.5.0: java/jni/CMakeFiles/javatinyb.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/pi/Desktop/tinyb-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Linking CXX shared library libjavatinyb.so"
	cd /home/pi/Desktop/tinyb-master/build/java/jni && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/javatinyb.dir/link.txt --verbose=$(VERBOSE)
	cd /home/pi/Desktop/tinyb-master/build/java/jni && $(CMAKE_COMMAND) -E cmake_symlink_library libjavatinyb.so.0.5.0 libjavatinyb.so.0 libjavatinyb.so

java/jni/libjavatinyb.so.0: java/jni/libjavatinyb.so.0.5.0
	@$(CMAKE_COMMAND) -E touch_nocreate java/jni/libjavatinyb.so.0

java/jni/libjavatinyb.so: java/jni/libjavatinyb.so.0.5.0
	@$(CMAKE_COMMAND) -E touch_nocreate java/jni/libjavatinyb.so

# Rule to build all files generated by this target.
java/jni/CMakeFiles/javatinyb.dir/build: java/jni/libjavatinyb.so

.PHONY : java/jni/CMakeFiles/javatinyb.dir/build

java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o.requires
java/jni/CMakeFiles/javatinyb.dir/requires: java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o.requires

.PHONY : java/jni/CMakeFiles/javatinyb.dir/requires

java/jni/CMakeFiles/javatinyb.dir/clean:
	cd /home/pi/Desktop/tinyb-master/build/java/jni && $(CMAKE_COMMAND) -P CMakeFiles/javatinyb.dir/cmake_clean.cmake
.PHONY : java/jni/CMakeFiles/javatinyb.dir/clean

java/jni/CMakeFiles/javatinyb.dir/depend:
	cd /home/pi/Desktop/tinyb-master/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/pi/Desktop/tinyb-master /home/pi/Desktop/tinyb-master/java/jni /home/pi/Desktop/tinyb-master/build /home/pi/Desktop/tinyb-master/build/java/jni /home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : java/jni/CMakeFiles/javatinyb.dir/depend

