# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  "CXX"
  )
# The set of files for implicit dependencies of each language:
set(CMAKE_DEPENDS_CHECK_CXX
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothAdapter.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothDevice.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothEvent.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothGattCharacteristic.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothGattDescriptor.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothGattService.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothManager.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/BluetoothObject.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/JNIMem.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o"
  "/home/pi/Desktop/tinyb-master/java/jni/helper.cxx" "/home/pi/Desktop/tinyb-master/build/java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o"
  )
set(CMAKE_CXX_COMPILER_ID "GNU")

# The include file search paths:
set(CMAKE_CXX_TARGET_INCLUDE_PATH
  "/usr/lib/jvm/java-8-openjdk-armhf/include"
  "/usr/lib/jvm/java-8-openjdk-armhf/include/linux"
  "../api"
  "../api/tinyb"
  "../include"
  "java/CMakeFiles/tinybjar.dir/jni"
  )

# Pairs of files generated by the same build rule.
set(CMAKE_MULTIPLE_OUTPUT_PAIRS
  "/home/pi/Desktop/tinyb-master/build/java/jni/libjavatinyb.so" "/home/pi/Desktop/tinyb-master/build/java/jni/libjavatinyb.so.0.5.0"
  "/home/pi/Desktop/tinyb-master/build/java/jni/libjavatinyb.so.0" "/home/pi/Desktop/tinyb-master/build/java/jni/libjavatinyb.so.0.5.0"
  )


# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  "/home/pi/Desktop/tinyb-master/build/src/CMakeFiles/tinyb.dir/DependInfo.cmake"
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
