# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# compile CXX with /usr/bin/c++
CXX_FLAGS = -fPIC   -Wall -Wextra -std=gnu++11

CXX_DEFINES = -Djavatinyb_EXPORTS

CXX_INCLUDES = -I/usr/lib/jvm/java-8-openjdk-armhf/include -I/usr/lib/jvm/java-8-openjdk-armhf/include/linux -I/home/pi/Desktop/tinyb-master/api -I/home/pi/Desktop/tinyb-master/api/tinyb -I/home/pi/Desktop/tinyb-master/include -I/home/pi/Desktop/tinyb-master/build/java/CMakeFiles/tinybjar.dir/jni 

